on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Load binary archives"
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: release

      - name: "Publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PATTERN='[0-9]{8}-[a-z0-9]{7}'
          OLD_RELEASES=$(gh release list | egrep $PATTERN | awk '{ print $1 }')
          for RELEASE in $OLD_RELEASES; do
            gh release delete $RELEASE
          done
          for TAG in $(git tag); do
            echo $TAG | egrep $PATTERN
            if [ "$?" == "0" ]; then
              git push --delete origin $TAG
            fi
          done
          TAG=$(date +%Y%m%d)-$(git describe --always)
          gh release create -p -n "Flightctl CLI pre-release" $TAG release/*

